#ifndef KEY_H
#define KEY_H

// 0.69 53	Next	9
// 0.34 26	Prev	10
// 2.31	178	V-		3
// 2.94	227 Menu	1
// 2.60	201	V+		12
// 0.94 73	GPS		18
// 2.11	163	OPEN	14	

const uchar KeyValue[] = {250,229,202,182,164,139,121,98,71,51,27};

#define KEY_PANEL	21
#define KEY_HOME	1
#define KEY_MODE0	6
#define KEY_RETRUN	5
#define KEY_VOLU	3
#define KEY_VOLD	2
#define KEY_OPEN	4

#define KEY_STOP	20
#define KEY_MUTE	12
#define KEY_DVD		19
#define KEY_MODE	15
#define KEY_MEDIA	11
#define KEY_FM		16
#define KEY_BT		7

#define KEY_PIC		14
#define KEY_NEXT	10
#define KEY_PREV	9
#define KEY_PP		8
#define KEY_TV		17
#define KEY_NAVI	18
#define KEY_SOUND	13

const uchar ButtValue[] = {8,39,39*2,39*3,39*4,39*5,39*6};
// nokey 0
// key 1-30
// ir  31-127
// wheel ad value 128-255
#define IRC_NULL  0
#define IRC_POWER 31
#define IRC_MUTE  32

#define IRC_OPEN  34
#define IRC_BAND  35
#define IRC_DVDTV 36
#define IRC_NAVIAV 37
//for DVD
#define IRC_GOTO  38
#define IRC_KEY1  39
#define IRC_KEY2  40
#define IRC_KEY3  41
#define IRC_KEY4  42
#define IRC_KEY5  43
#define IRC_KEY6  44
#define IRC_KEY7  45
#define IRC_KEY8  46
#define IRC_KEY9  47
#define IRC_KEY10 48
#define IRC_KEY0  49
#define IRC_UP  50
#define IRC_DOWN  51
#define IRC_LEFT  52
#define IRC_RIGHT  53
#define IRC_OK  54
#define IRC_ZOOM  55
#define IRC_RND  56
#define IRC_REP  57
#define IRC_TITLE 58
#define IRC_RETURN 59
#define IRC_PREV  60
#define IRC_NEXT  61
#define IRC_FWARD  62
#define IRC_BWARD  63
#define IRC_PLAY  64
#define IRC_STOP  65
#define IRC_ANGEL 66
#define IRC_PBC	  67
#define IRC_SUBT 68
#define IRC_AUDIO 69
#define IRC_DISPLAY 70
#define IRC_SETUP 71
#define IRC_SEL	72
#define IRC_SLOW	73
#define IRC_PROG	74

#define IRC_VUP  90
#define IRC_VDOWN  91
#define IRC_DVDCARD  93
#define IRC_MODE  94

#define IRC_NAVI 18
#define IRC_TV 17
#define IRC_RADIO 16
 
//#define BS_KOA 
#ifdef BS_KOA

const uchar KeyMap[256] = 
{
/*  	0			1			2			3			4			5			6			7			8			9			A			B			C			D			E			F		*/
/* 0 */	IRC_DVDCARD,IRC_BWARD,	IRC_GOTO,	IRC_REP,	IRC_NULL,	IRC_NULL,	IRC_PBC,	IRC_SETUP,	IRC_TV,		IRC_DISPLAY,IRC_KEY2,	IRC_NULL,	IRC_NULL,	IRC_KEY6,	IRC_FWARD,	IRC_TITLE,   //0x0-0xF
/* 1 */	IRC_RADIO,	IRC_RIGHT,	IRC_DOWN,	IRC_NULL,	IRC_OPEN,	IRC_DVDTV,	IRC_NULL,	IRC_NAVI,	IRC_PLAY,	IRC_VDOWN,  IRC_VUP,	IRC_OK,		IRC_NULL,	IRC_VUP,	IRC_PLAY,	IRC_KEY4, 	//0x10-0x1F   
/* 2 */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_DVDTV,	IRC_NULL,	IRC_SUBT,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* 3 */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* 4 */	IRC_KEY3,	IRC_UP,		IRC_NULL,	IRC_AUDIO,	IRC_KEY5,	IRC_KEY7,	IRC_DISPLAY,IRC_KEY1,	IRC_ZOOM,	IRC_SUBT,	IRC_LEFT,	IRC_NULL,	IRC_MUTE,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* 5 */	IRC_KEY8,	IRC_NEXT,	IRC_NEXT,	IRC_STOP,	IRC_NULL,	IRC_PREV,	IRC_NAVI,	IRC_RND,	IRC_NULL,	IRC_ANGEL,	IRC_NULL,	IRC_NULL,	IRC_KEY10,	IRC_KEY0,	IRC_KEY9,	IRC_FWARD,
/* 6 */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* 7 */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* 8 */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* 9 */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* A */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* B */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* C */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* D */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* E */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* F */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
};

#else

const uchar KeyMap[256] = 
{
/*  	0			1			2			3			4			5			6			7			8			9			A			B			C			D			E			F		*/
/* 0 */	IRC_NULL,	IRC_KEY10,	IRC_AUDIO,	IRC_NEXT,	IRC_NULL,	IRC_SEL,	IRC_PREV,	IRC_DISPLAY,IRC_SLOW,	IRC_BAND,	IRC_KEY5,	IRC_NULL,	IRC_NULL,	IRC_SUBT,	IRC_KEY7,	IRC_KEY3,   //0x0-0xF
/* 1 */	IRC_NULL,	IRC_RIGHT,	IRC_DOWN,	IRC_NULL,	IRC_POWER,	IRC_SETUP,	IRC_NULL,	IRC_STOP,	IRC_KEY1,	IRC_LEFT,  	IRC_KEY8,	IRC_OK,		IRC_NULL,	IRC_UP,		IRC_KEY6,	IRC_TITLE, 	//0x10-0x1F   
/* 2 */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_SUBT,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* 3 */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* 4 */	IRC_VDOWN,	IRC_PLAY,	IRC_NULL,	IRC_NULL,	IRC_KEY2,	IRC_GOTO,	IRC_MUTE,	IRC_PBC,	IRC_VUP,	IRC_NULL,	IRC_ZOOM,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* 5 */	IRC_REP,	IRC_KEY4,	IRC_KEY0,	IRC_KEY9,	IRC_NULL,	IRC_PROG,	IRC_NULL,	IRC_MODE,	IRC_NULL,	IRC_ANGEL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_RND,	IRC_NULL,
/* 6 */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* 7 */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* 8 */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* 9 */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* A */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* B */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* C */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* D */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* E */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
/* F */	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,	IRC_NULL,
};

#endif
#endif