/*****************************************************************************************
*
*       File Name   :	NexEffecter.h
*		Module		:	Nextreaming Image Library
*       Description :	Main header
*
******************************************************************************************
                         Nextreaming Confidential Proprietary
                     Copyright (C) 2002 Nextreaming Corporation
                 All rights are reserved by Nextreaming Corporation

Revision History:
Author              Date			Version		Description of Changes
------------------------------------------------------------------------------------------
Hyun-nam, Park		2005/08/26		3.0			Draft
----------------------------------------------------------------------------------------*/

#ifndef NEXEFFECTER_H
#define NEXEFFECTER_H


///////////////////////////////////////////////////////////////////////////////
// Definitions
///////////////////////////////////////////////////////////////////////////////

//
// Image max size
//
#define NEXIMAGE_IMAGE_MAXWIDTH								4096
#define NEXIMAGE_IMAGE_MAXHEIGHT							4096

//
// NexImage errors
//
#define NEXIMAGEERR_OK										0x00000000
#define NEXIMAGEERR_FAIL									0x00000001
#define NEXIMAGEERR_NULLINPUTPARAMETER						0x00000002
#define NEXIMAGEERR_INVALIDPARAMETER						0x00000003
#define NEXIMAGEERR_NOTIMPLEMENTED							0x00000004
#define NEXIMAGEERR_INVALIDBUFFERALIGN						0x00000005

//
// NexImage pixel format
//
#define NEXIMAGE_PIXELFORMAT_MASK							0x000000FF

#define NEXIMAGE_PIXELFORMAT_UNKNOWN						0x00000000
#define NEXIMAGE_PIXELFORMAT_GRAY256						0x00000001
#define NEXIMAGE_PIXELFORMAT_YUV420_256						0x00000002
#define NEXIMAGE_PIXELFORMAT_YUV420_BT601					0x00000003
#define NEXIMAGE_PIXELFORMAT_YUV422_256						0x00000004
#define NEXIMAGE_PIXELFORMAT_YUV422_BT601					0x00000005
#define NEXIMAGE_PIXELFORMAT_RGB565							0x00000006
#define NEXIMAGE_PIXELFORMAT_BGR565							0x00000007
#define NEXIMAGE_PIXELFORMAT_RGB888							0x00000008
#define NEXIMAGE_PIXELFORMAT_BGR888							0x00000009
#define NEXIMAGE_PIXELFORMAT_RGB32							0x0000000A
#define NEXIMAGE_PIXELFORMAT_BGR32							0x0000000B
#define NEXIMAGE_PIXELFORMAT_MAX							0x0000000B

//
// NexImage macro pixel format
//	- Packed YUV support
//	- If available build, NEXIMAGE_PFCAPS_MACROPIXEL is set.
// 
#define NEXIMAGE_MACROPIXEL_MASK							0x0000FF00
#define NEXIMAGE_MACROPIXEL_SHIFT							8

// Packed 422 format
#define NEXIMAGE_MACROPIXEL_UNKNOWN							0x00000000
#define NEXIMAGE_MACROPIXEL_YUYV							0x00000100
#define NEXIMAGE_MACROPIXEL_YVYU							0x00000200
#define NEXIMAGE_MACROPIXEL_UYVY							0x00000300
#define NEXIMAGE_MACROPIXEL_VYUY							0x00000400
#define NEXIMAGE_MACROPIXEL_UYYV							0x00000500
#define NEXIMAGE_MACROPIXEL_VYYU							0x00000600
#define NEXIMAGE_MACROPIXEL_MAX								0x00000600

//
// NexImage optional pixel format
//
// Restricted usage
//
#define NEXIMAGE_OPTIONPF_MASK								0x00FF0000

#define NEXIMAGE_OPTIONPF_NORMAL							0x00000000
#define NEXIMAGE_OPTIONPF_FORCERGB555						0x00010000

// Pixel format caps
#define NEXIMAGE_PFCAPS_GREY								0x0001
#define NEXIMAGE_PFCAPS_YUV420								0x0002
#define NEXIMAGE_PFCAPS_YUV422								0x0004
#define NEXIMAGE_PFCAPS_RGB565								0x0008
#define NEXIMAGE_PFCAPS_RGB888								0x0010
#define NEXIMAGE_PFCAPS_RGB32								0x0020
#define NEXIMAGE_PFCAPS_YUVPLANAR							0x8000
#define NEXIMAGE_PFCAPS_MACROPIXEL							0x4000

//
// NexImage basic image operation ID
//
#define NEXIMAGE_BASICOPERATIONID_UNKNOWN					0x00000000
#define NEXIMAGE_BASICOPERATIONID_COPY						0x00000001
#define NEXIMAGE_BASICOPERATIONID_ADD						0x00000002
#define NEXIMAGE_BASICOPERATIONID_SUBTRACT					0x00000003
#define NEXIMAGE_BASICOPERATIONID_MULTIPLY					0x00000004
#define NEXIMAGE_BASICOPERATIONID_AND						0x00000005
#define NEXIMAGE_BASICOPERATIONID_OR						0x00000006
#define NEXIMAGE_BASICOPERATIONID_XOR						0x00000007
#define NEXIMAGE_BASICOPERATIONID_DARKEN					0x00000008
#define NEXIMAGE_BASICOPERATIONID_BRIGHTEN					0x00000009
#define NEXIMAGE_BASICOPERATIONID_AVERAGE					0x0000000A
#define NEXIMAGE_BASICOPERATIONID_MAX						0x0000000A

//
// NexImage simple transformation ID
//
#define NEXIMAGE_SIMPLETRANSFORMID_UNKNOWN					0x00000000
#define NEXIMAGE_SIMPLETRANSFORMID_MIRROR					0x00000001
#define NEXIMAGE_SIMPLETRANSFORMID_FLIP						0x00000002
#define NEXIMAGE_SIMPLETRANSFORMID_ROTATE90					0x00000003
#define NEXIMAGE_SIMPLETRANSFORMID_ROTATE180				0x00000004
#define NEXIMAGE_SIMPLETRANSFORMID_ROTATE270				0x00000005
#define NEXIMAGE_SIMPLETRANSFORMID_RESIZE_NN				0x00000006
#define NEXIMAGE_SIMPLETRANSFORMID_RESIZE_BL				0x00000007
#define NEXIMAGE_SIMPLETRANSFORMID_MAX						0x00000007

//
// Neximage painting ID
//
#define NEXIMAGE_PAINTID_UNKNOWN							0x00000000
#define NEXIMAGE_PAINTID_BLT								0x00000001
#define NEXIMAGE_PAINTID_MAKEFRAME							0x00000002
#define NEXIMAGE_PAINTID_MAX								0x00000002

// Paint operation flag for blt
#define NEXIMAGE_PAINTOPFLAG_BLTMASK						0x0000000F
#define NEXIMAGE_PAINTOPFLAG_COPY							0x00000000
#define NEXIMAGE_PAINTOPFLAG_ALPHABLENDING					0x00000001
#define NEXIMAGE_PAINTOPFLAG_MASKBLENDING					0x00000002

// Paint operation flag for make frame
#define NEXIMAGE_PAINTOPFLAG_ALPHAFRAME						0x00000000
#define NEXIMAGE_PAINTOPFLAG_MASKFRAME						0x00000001
#define NEXIMAGE_PAINTOPFLAG_USETRANSCOLOR					0x00000010
#define NEXIMAGE_PAINTOPFLAG_USEALPHAVALUE					0x00000020
#define NEXIMAGE_PAINTOPFLAG_BYTEALIGNEDINPUT				0x00000040

//
// NexImage color adjustment ID
//
#define NEXIMAGE_COLORADJUSTID_UNKNOWN						0x00000000
#define NEXIMAGE_COLORADJUSTID_GREYIMAGE					0x00000001
#define NEXIMAGE_COLORADJUSTID_POSTERIZE					0x00000002
#define NEXIMAGE_COLORADJUSTID_BRIGHTNESS					0x00000003
#define NEXIMAGE_COLORADJUSTID_CONTRAST						0x00000004
#define NEXIMAGE_COLORADJUSTID_HISTOGRAM_EQ					0x00000005
#define NEXIMAGE_COLORADJUSTID_HISTOGRAM_STRETCH			0x00000006
#define NEXIMAGE_COLORADJUSTID_MAX							0x00000006

//
// NexImage effect ID
//
#define NEXIMAGE_EFFECTID_UNKNOWN							0x00000000
#define NEXIMAGE_EFFECTID_GAUSSIAN							0x00000001
#define NEXIMAGE_EFFECTID_MEAN								0x00000002
#define NEXIMAGE_EFFECTID_WIND_BLUR							0x00000003
#define NEXIMAGE_EFFECTID_MEDIAN							0x00000004
#define NEXIMAGE_EFFECTID_SHARPEN							0x00000005
#define NEXIMAGE_EFFECTID_SOBEL								0x00000006
#define NEXIMAGE_EFFECTID_WIND_DISTORTION					0x00000007
#define NEXIMAGE_EFFECTID_SPHERIZE							0x00000008
#define NEXIMAGE_EFFECTID_THIN								0x00000009
#define NEXIMAGE_EFFECTID_DIFFUSE_GLOW						0x0000000A
#define NEXIMAGE_EFFECTID_WATER_REFLECTION					0x0000000B
#define NEXIMAGE_EFFECTID_MOSAIC							0x0000000C
#define NEXIMAGE_EFFECTID_EMBOSS							0x0000000D
#define NEXIMAGE_EFFECTID_OLD_FILM							0x0000000E
#define NEXIMAGE_EFFECTID_GORGEOUS							0x0000000F
#define NEXIMAGE_EFFECTID_MONOCHROME_PEN					0x00000010
#define NEXIMAGE_EFFECTID_EDGE_NEON							0x00000011
#define NEXIMAGE_EFFECTID_WOODCUT							0x00000012
#define NEXIMAGE_EFFECTID_OILPAINT							0x00000013
#define NEXIMAGE_EFFECTID_NEGATIVE							0x00000014
#define NEXIMAGE_EFFECTID_POSTERIZE							0x00000015
#define NEXIMAGE_EFFECTID_SOLARIZE							0x00000016
#define NEXIMAGE_EFFECTID_COLOR_TONE						0x00000017
#define NEXIMAGE_EFFECTID_UV_SELECTION						0x00000018
#define NEXIMAGE_EFFECTID_MAX								0x00000018

// Effect operation flag
#define NEXIMAGE_EFFECTOPFLAG_ONLYLUMINANCE					0x00000000
#define NEXIMAGE_EFFECTOPFLAG_ALLCHANNELS					0x00000001

// Effect direction
#define NEXIMAGE_EFFECTDIRECTION_RIGHT						0
#define NEXIMAGE_EFFECTDIRECTION_DOWN						1
#define NEXIMAGE_EFFECTDIRECTION_LEFT						2
#define NEXIMAGE_EFFECTDIRECTION_UP							3

#define NEXIMAGE_EFFECTDIRECTION_HORIZONTAL					4
#define NEXIMAGE_EFFECTDIRECTION_VERTICAL					5

#define NEXIMAGE_EFFECTDIRECTION_ULDR						6			// Up-Left to Down-Right
#define NEXIMAGE_EFFECTDIRECTION_DLUR						7			// Down-Left to Up-Right
#define NEXIMAGE_EFFECTDIRECTION_DRUL						8			// Down-Right to Up-Left
#define NEXIMAGE_EFFECTDIRECTION_URDL						9			// Up-Right to Down-Left

// Effect filter size
#define NEXIMAGE_EFFECT_MAX_FILTERSIZE						15

//
// Effect dependent definitions
//

// NEXIMAGE_EFFECTID_SOBEL effect
#define NEXIMAGE_SOBELOPFLAG_OPMASK							0x00FF0000
#define NEXIMAGE_SOBELOPFLAG_FORCEBINARY					0x00010000

// NEXIMAGE_EFFECTID_DIFFUSE_GLOW effect
#define NEXIMAGE_DIFFUSEGLOW_MINSIZE						5
#define NEXIMAGE_DIFFUSEGLOW_MAXSIZE						41
#define NEXIMAGE_DIFFUSEGLOW_DEFSIZE						31

#define NEXIMAGE_DIFFUSEGLOW_MINSTRENGTH					1
#define NEXIMAGE_DIFFUSEGLOW_MAXSTRENGTH					8
#define NEXIMAGE_DIFFUSEGLOW_DEFSTRENGTH					3

// NEXIMAGE_EFFECTID_COLOR_TONE effect
#define NEXIMAGE_COLOTONEUV_GREY							0x00008080
#define NEXIMAGE_COLOTONEUV_SEPIA							0x0000B050
#define NEXIMAGE_COLOTONEUV_PURPLE							0x0000B080
#define NEXIMAGE_COLOTONEUV_BLUE							0x000050B0
#define NEXIMAGE_COLOTONEUV_GREEN							0x00005050

// NEXIMAGE_EFFECTID_UV_SELECTION effect
// Single color area
#define NEXIMAGE_UVSELECT_RED								0x00000001
#define NEXIMAGE_UVSELECT_ORANGE							0x00000004
#define NEXIMAGE_UVSELECT_YELLOW							0x00000010
#define NEXIMAGE_UVSELECT_SPRING							0x00000040
#define NEXIMAGE_UVSELECT_GREEN								0x00000100
#define NEXIMAGE_UVSELECT_TEAL								0x00000400
#define NEXIMAGE_UVSELECT_CYAN								0x00001000
#define NEXIMAGE_UVSELECT_AZURE								0x00004000
#define NEXIMAGE_UVSELECT_BLUE								0x00010000
#define NEXIMAGE_UVSELECT_VIOLET							0x00040000
#define NEXIMAGE_UVSELECT_MAGENTA							0x00100000
#define NEXIMAGE_UVSELECT_PINK								0x00400000

// Wide color area
#define NEXIMAGE_UVSELECT_REDWIDE							(NEXIMAGE_UVSELECT_PINK|NEXIMAGE_UVSELECT_RED|NEXIMAGE_UVSELECT_ORANGE)
#define NEXIMAGE_UVSELECT_YELLOWWIDE						(NEXIMAGE_UVSELECT_ORANGE|NEXIMAGE_UVSELECT_YELLOW|NEXIMAGE_UVSELECT_SPRING)
#define NEXIMAGE_UVSELECT_GREENWIDE							(NEXIMAGE_UVSELECT_SPRING|NEXIMAGE_UVSELECT_GREEN|NEXIMAGE_UVSELECT_TEAL)
#define NEXIMAGE_UVSELECT_CYANWIDE							(NEXIMAGE_UVSELECT_TEAL|NEXIMAGE_UVSELECT_CYAN|NEXIMAGE_UVSELECT_AZURE)
#define NEXIMAGE_UVSELECT_BLUEWIDE							(NEXIMAGE_UVSELECT_AZURE|NEXIMAGE_UVSELECT_BLUE|NEXIMAGE_UVSELECT_VIOLET)
#define NEXIMAGE_UVSELECT_MAGENTAWIDE						(NEXIMAGE_UVSELECT_VIOLET|NEXIMAGE_UVSELECT_MAGENTA|NEXIMAGE_UVSELECT_PINK)

// Except color area
#define NEXIMAGE_UVSELECT_ALLCOLOR							(NEXIMAGE_UVSELECT_RED|NEXIMAGE_UVSELECT_ORANGE|NEXIMAGE_UVSELECT_YELLOW|NEXIMAGE_UVSELECT_SPRING|NEXIMAGE_UVSELECT_GREEN|NEXIMAGE_UVSELECT_TEAL|NEXIMAGE_UVSELECT_CYAN|NEXIMAGE_UVSELECT_AZURE|NEXIMAGE_UVSELECT_BLUE|NEXIMAGE_UVSELECT_VIOLET|NEXIMAGE_UVSELECT_MAGENTA|NEXIMAGE_UVSELECT_PINK)
#define NEXIMAGE_UVSELECT_NORED								(NEXIMAGE_UVSELECT_ORANGE|NEXIMAGE_UVSELECT_YELLOW|NEXIMAGE_UVSELECT_SPRING|NEXIMAGE_UVSELECT_GREEN|NEXIMAGE_UVSELECT_TEAL|NEXIMAGE_UVSELECT_CYAN|NEXIMAGE_UVSELECT_AZURE|NEXIMAGE_UVSELECT_BLUE|NEXIMAGE_UVSELECT_VIOLET|NEXIMAGE_UVSELECT_MAGENTA|NEXIMAGE_UVSELECT_PINK)
#define NEXIMAGE_UVSELECT_NOYELLOW							(NEXIMAGE_UVSELECT_RED|NEXIMAGE_UVSELECT_ORANGE|NEXIMAGE_UVSELECT_SPRING|NEXIMAGE_UVSELECT_GREEN|NEXIMAGE_UVSELECT_TEAL|NEXIMAGE_UVSELECT_CYAN|NEXIMAGE_UVSELECT_AZURE|NEXIMAGE_UVSELECT_BLUE|NEXIMAGE_UVSELECT_VIOLET|NEXIMAGE_UVSELECT_MAGENTA|NEXIMAGE_UVSELECT_PINK)
#define NEXIMAGE_UVSELECT_NOGREEN							(NEXIMAGE_UVSELECT_RED|NEXIMAGE_UVSELECT_ORANGE|NEXIMAGE_UVSELECT_YELLOW|NEXIMAGE_UVSELECT_SPRING|NEXIMAGE_UVSELECT_TEAL|NEXIMAGE_UVSELECT_CYAN|NEXIMAGE_UVSELECT_AZURE|NEXIMAGE_UVSELECT_BLUE|NEXIMAGE_UVSELECT_VIOLET|NEXIMAGE_UVSELECT_MAGENTA|NEXIMAGE_UVSELECT_PINK)
#define NEXIMAGE_UVSELECT_NOCYAN							(NEXIMAGE_UVSELECT_RED|NEXIMAGE_UVSELECT_ORANGE|NEXIMAGE_UVSELECT_YELLOW|NEXIMAGE_UVSELECT_SPRING|NEXIMAGE_UVSELECT_GREEN|NEXIMAGE_UVSELECT_TEAL|NEXIMAGE_UVSELECT_AZURE|NEXIMAGE_UVSELECT_BLUE|NEXIMAGE_UVSELECT_VIOLET|NEXIMAGE_UVSELECT_MAGENTA|NEXIMAGE_UVSELECT_PINK)
#define NEXIMAGE_UVSELECT_NOBLUE							(NEXIMAGE_UVSELECT_RED|NEXIMAGE_UVSELECT_ORANGE|NEXIMAGE_UVSELECT_YELLOW|NEXIMAGE_UVSELECT_SPRING|NEXIMAGE_UVSELECT_GREEN|NEXIMAGE_UVSELECT_TEAL|NEXIMAGE_UVSELECT_CYAN|NEXIMAGE_UVSELECT_AZURE|NEXIMAGE_UVSELECT_VIOLET|NEXIMAGE_UVSELECT_MAGENTA|NEXIMAGE_UVSELECT_PINK)
#define NEXIMAGE_UVSELECT_NOMAGENTA							(NEXIMAGE_UVSELECT_RED|NEXIMAGE_UVSELECT_ORANGE|NEXIMAGE_UVSELECT_YELLOW|NEXIMAGE_UVSELECT_SPRING|NEXIMAGE_UVSELECT_GREEN|NEXIMAGE_UVSELECT_TEAL|NEXIMAGE_UVSELECT_CYAN|NEXIMAGE_UVSELECT_AZURE|NEXIMAGE_UVSELECT_BLUE|NEXIMAGE_UVSELECT_VIOLET|NEXIMAGE_UVSELECT_PINK)

// Except wide color area
#define NEXIMAGE_UVSELECT_NOREDWIDE							(NEXIMAGE_UVSELECT_YELLOW|NEXIMAGE_UVSELECT_SPRING|NEXIMAGE_UVSELECT_GREEN|NEXIMAGE_UVSELECT_TEAL|NEXIMAGE_UVSELECT_CYAN|NEXIMAGE_UVSELECT_AZURE|NEXIMAGE_UVSELECT_BLUE|NEXIMAGE_UVSELECT_VIOLET|NEXIMAGE_UVSELECT_MAGENTA)
#define NEXIMAGE_UVSELECT_NOYELLOWWIDE						(NEXIMAGE_UVSELECT_RED|NEXIMAGE_UVSELECT_GREEN|NEXIMAGE_UVSELECT_TEAL|NEXIMAGE_UVSELECT_CYAN|NEXIMAGE_UVSELECT_AZURE|NEXIMAGE_UVSELECT_BLUE|NEXIMAGE_UVSELECT_VIOLET|NEXIMAGE_UVSELECT_MAGENTA|NEXIMAGE_UVSELECT_PINK)
#define NEXIMAGE_UVSELECT_NOGREENWIDE						(NEXIMAGE_UVSELECT_RED|NEXIMAGE_UVSELECT_ORANGE|NEXIMAGE_UVSELECT_YELLOW|NEXIMAGE_UVSELECT_CYAN|NEXIMAGE_UVSELECT_AZURE|NEXIMAGE_UVSELECT_BLUE|NEXIMAGE_UVSELECT_VIOLET|NEXIMAGE_UVSELECT_MAGENTA|NEXIMAGE_UVSELECT_PINK)
#define NEXIMAGE_UVSELECT_NOCYANWIDE						(NEXIMAGE_UVSELECT_RED|NEXIMAGE_UVSELECT_ORANGE|NEXIMAGE_UVSELECT_YELLOW|NEXIMAGE_UVSELECT_SPRING|NEXIMAGE_UVSELECT_GREEN|NEXIMAGE_UVSELECT_BLUE|NEXIMAGE_UVSELECT_VIOLET|NEXIMAGE_UVSELECT_MAGENTA|NEXIMAGE_UVSELECT_PINK)
#define NEXIMAGE_UVSELECT_NOBLUEWIDE						(NEXIMAGE_UVSELECT_RED|NEXIMAGE_UVSELECT_ORANGE|NEXIMAGE_UVSELECT_YELLOW|NEXIMAGE_UVSELECT_SPRING|NEXIMAGE_UVSELECT_GREEN|NEXIMAGE_UVSELECT_TEAL|NEXIMAGE_UVSELECT_CYAN|NEXIMAGE_UVSELECT_MAGENTA|NEXIMAGE_UVSELECT_PINK)
#define NEXIMAGE_UVSELECT_NOMAGENTAWIDE						(NEXIMAGE_UVSELECT_RED|NEXIMAGE_UVSELECT_ORANGE|NEXIMAGE_UVSELECT_YELLOW|NEXIMAGE_UVSELECT_SPRING|NEXIMAGE_UVSELECT_GREEN|NEXIMAGE_UVSELECT_TEAL|NEXIMAGE_UVSELECT_CYAN|NEXIMAGE_UVSELECT_AZURE|NEXIMAGE_UVSELECT_BLUE)

//
// NexImage transition
//

// Transition effect ID
#define NEXIMAGE_TRANSITIONID_NONE							0x00000000
#define NEXIMAGE_TRANSITIONID_BLIND							0x00000001	// 블라인드
#define NEXIMAGE_TRANSITIONID_COVER							0x00000002	// 덥기
#define NEXIMAGE_TRANSITIONID_UNCOVER						0x00000003	// 당기기
#define NEXIMAGE_TRANSITIONID_RANDOM						0x00000004	// 랜덤(Dissolve,흩어뿌리기)
#define NEXIMAGE_TRANSITIONID_FADEWITHBLACK					0x00000005	// 검정에서 나타나기(Fade out/in)
#define NEXIMAGE_TRANSITIONID_OVERLAP						0x00000006	// 흐려졌다 나타나기(Overlap)
#define NEXIMAGE_TRANSITIONID_WIPE							0x00000007	// 닦아내기
#define NEXIMAGE_TRANSITIONID_BOX							0x00000008	// 사각형
#define NEXIMAGE_TRANSITIONID_CHECKERBOARD					0x00000009	// 체크무늬
#define NEXIMAGE_TRANSITIONID_COMB							0x0000000A	// 빗질
#define NEXIMAGE_TRANSITIONID_PUSH							0x0000000B	// 밀어내기
#define NEXIMAGE_TRANSITIONID_SPLIT							0x0000000C	// 나누기
#define NEXIMAGE_TRANSITIONID_STRIPS						0x0000000D	// 계단 모양
#define NEXIMAGE_TRANSITIONID_WEDGE							0x0000000E	// V자 모양
#define NEXIMAGE_TRANSITIONID_WHEEL							0x0000000F	// 시계 방향 회전
#define NEXIMAGE_TRANSITIONID_SHAPE							0x00000010	// 모양으로 펼치기
#define NEXIMAGE_TRANSITIONID_NEWFLASH						0x00000011	// 회전하며 확대하기
#define NEXIMAGE_TRANSITIONID_MAX							0x00000012

// Transition effect operation flags
#define NEXIMAGE_TRANSITIONOPFLAG_NORMAL					0x00000000
#define NEXIMAGE_TRANSITIONOPFLAG_MAX						0x00000000

// Transition effect direction code
#define NEXIMAGE_TRANSITIONDIRECTION_UP						0x00000000
#define NEXIMAGE_TRANSITIONDIRECTION_RIGHTUP				0x00000001
#define NEXIMAGE_TRANSITIONDIRECTION_RIGHT					0x00000002
#define NEXIMAGE_TRANSITIONDIRECTION_RIGHTDOWN				0x00000003
#define NEXIMAGE_TRANSITIONDIRECTION_DOWN					0x00000004
#define NEXIMAGE_TRANSITIONDIRECTION_LEFTDOWN				0x00000005
#define NEXIMAGE_TRANSITIONDIRECTION_LEFT					0x00000006
#define NEXIMAGE_TRANSITIONDIRECTION_LEFTUP					0x00000007

// Transition effect direction flags
#define NEXIMAGE_TRANSITIONDIRECTION_HORIZONTAL				0x00000000
#define NEXIMAGE_TRANSITIONDIRECTION_VERTICAL				0x00000010

#define NEXIMAGE_TRANSITIONDIRECTION_INSIDE					0x00000000
#define NEXIMAGE_TRANSITIONDIRECTION_OUTSIDE				0x00000020

#define NEXIMAGE_TRANSITIONDIRECTION_CLOCKWISE				0x00000000
#define NEXIMAGE_TRANSITIONDIRECTION_COUNTERCLOCKWISE		0x00000040

// Transition effect shpae
#define NEXIMAGE_TRANSITIONSHAPE_NONE						0x00000000
#define NEXIMAGE_TRANSITIONSHAPE_DOT						0x00000001
#define NEXIMAGE_TRANSITIONSHAPE_BAR						0x00000002
#define NEXIMAGE_TRANSITIONSHAPE_CIRCLE						0x00000003
#define NEXIMAGE_TRANSITIONSHAPE_DIAMOND					0x00000004
#define NEXIMAGE_TRANSITIONSHAPE_PLUS						0x00000005

// Transition effect division count constant
#define NEXIMAGE_TRANSITIONDIV_STATICBLOCKSIZE				0x00000000


///////////////////////////////////////////////////////////////////////////////
// Types
///////////////////////////////////////////////////////////////////////////////

#ifdef WIN32
#pragma pack (1)
#endif

#ifdef SH3DSP
#pragma pack 1
#endif

// NexImage error type
typedef unsigned long NEXIMAGEERR;

// NexImage image parameter
typedef struct _tagNEXIMAGEIMG
{
	union
	{
		unsigned char	*pY;				// Y image buffer for YUV space
		unsigned char	*pRGB;				// RGB image buffer for RGB space
		unsigned long	ulCh1BufSize;		// Channel 1 buffer byte size
	} Channel1;

	union
	{
		unsigned char	*pUV;				// UV image buffer for YUV space ( Only interleaved format )
		unsigned char	*pU;				// U image buffer for YUV space ( Only planar format )
		unsigned long	ulCh2BufSize;		// Channel 2 buffer byte size
	} Channel2;

	union
	{
		unsigned char	*pV;				// V image buffer for YUV space ( Only planar format )
		unsigned long	ulCh3BufSize;		// Channel 2 buffer byte size
	} Channel3;

	int					iWidth;				// Image width
	int					iHeight;			// Image height
	int					iYPitch;			// Image channel 1 pitch
	int					iUVPitch;			// Image channel 2 pitch

	unsigned long		ulFormat;			// NEXIMAGE_PIXELFORMAT_XXX

} NEXIMAGEIMG, *PNEXIMAGEIMG;

// NexImage paint parameter
typedef struct _tagNEXIMAGEPaintPARAM
{
	unsigned long	ulPaintID;				// Paint ID
	
	unsigned long	ulOpFlags;				// Operation flag
	int				iXOffset;				// X start offset
	int				iYOffset;				// Y start offset
	int				iXSize;					// X drawing size
	int				iYSize;					// Y drawing size
	unsigned long	ulValue;				// Painting dependent value
	
} NEXIMAGEPaintPARAM, *PNEXIMAGEPaintPARAM;

// NexImage effect parameter
typedef struct _tagNEXIMAGEEffectPARAM
{
	unsigned long	ulEffectID;				// Effect ID
	
	unsigned long	ulOpFlags;				// Operation flag
	unsigned long	ulDirection;			// Direction
	unsigned long	ulFilterSize;			// Filter size
	unsigned long	ulColor;				// Color value
	long			lValue;					// Effect dependent value

} NEXIMAGEEffectPARAM, *PNEXIMAGEEffectPARAM;

// NexImage transition parameter
typedef struct _tagNEXIMAGETransitionPARAM
{
	unsigned long	ulEffectID;			// Effect ID
	
	unsigned long	ulOpFlags;			// Operation flag
	unsigned long	ulDirectionCode;	// Direction code
	unsigned long	ulDirectionFlags;	// Direction flag
	unsigned long	ulShape;			// Shape code
	unsigned long	ulDivisionCount;	// Division count number
	unsigned long	ulValue;			// Effect dependent value
	
	unsigned long	ulContext1;			// Library internal context. App must not modify it.
	unsigned long	ulContext2;			// Library internal context. App must not modify it.

} NEXIMAGETransitionPARAM, *PNEXIMAGETransitionPARAM;


#ifdef WIN32
#pragma pack ()
#endif

#ifdef SH3DSP
#pragma unpack
#endif


///////////////////////////////////////////////////////////////////////////////
// APIs
///////////////////////////////////////////////////////////////////////////////

#ifdef __cplusplus
extern "C" {
#endif

void NexImage_Init( void );
void NexImage_DeInit( void );

// Version API
char *NexImage_GetVersion( void );
char *NexImage_GetVersionInfo( void );
unsigned short NexImage_GetPixelFormatCaps( void );

// Utilities
NEXIMAGEERR NexImage_GetCompatibleBufferSize( PNEXIMAGEIMG pImage );
void *NexImage_SetDebugPrint( void (*pfnDebugPrintf)( char* strFormat, ... ) );

// Basic operations
NEXIMAGEERR NexImage_BasicOperation( PNEXIMAGEIMG pDestImage, PNEXIMAGEIMG pSrcImage, unsigned long ulOperation );

// Simple transformation
NEXIMAGEERR NexImage_SimpleTransform( PNEXIMAGEIMG pDestImage, PNEXIMAGEIMG pSrcImage, unsigned long ulOperation );

// Paint
NEXIMAGEERR NexImage_Paint( PNEXIMAGEIMG pDestImage, PNEXIMAGEIMG pSrcImage, PNEXIMAGEIMG pRefImage, PNEXIMAGEPaintPARAM pParam );

// Color conversion
NEXIMAGEERR NexImage_ColorConversion( PNEXIMAGEIMG pDestImage, PNEXIMAGEIMG pSrcImage );

// Color adjustment
NEXIMAGEERR NexImage_ColorAdjust( PNEXIMAGEIMG pDestImage, PNEXIMAGEIMG pSrcImage, PNEXIMAGEEffectPARAM pParam );

// Image effect
NEXIMAGEERR NexImage_Effect( PNEXIMAGEIMG pDestImage, PNEXIMAGEIMG pSrcImage, PNEXIMAGEEffectPARAM pParam );

// Transition effect
NEXIMAGEERR NexImage_Transition( PNEXIMAGEIMG pDestImage, PNEXIMAGEIMG pSrcImage1, PNEXIMAGEIMG pSrcImage2, PNEXIMAGETransitionPARAM pParam, unsigned long ulCurrent, unsigned long ulTotal );

#ifdef __cplusplus
}
#endif

#endif
