#pragma once

void call_setup_info(BYTE GroupID, BYTE GroupSubID);
void call_inquiry_info(BYTE PageCode);
void call_sysmode_info();
void call_temp_info();
void call_testtone_info();
void call_toc1_info(BYTE TrackNo);
void call_toc2_info(BYTE TrackNo);
void call_folder_file_no(WORD FolderNo, WORD FileNo);
void call_text_code_info(BYTE PageNo);
void call_text_info(BYTE TextType, BYTE TrackNo, BYTE PageNo, BYTE SelectInfo);
BOOL call_file_name_info(WORD FolderNo, WORD FileNo, BYTE PageNo, BYTE Extension, BYTE AdditionFileNs);
void call_folder_name_info(WORD FolderNo, BYTE PageNo, BYTE AdditionFolderNs) ;
void call_tag_info(BYTE TagType, BYTE PageNo, BYTE DataSelect);
void call_disc_name_info(BYTE PageNo);
void call_disc_info(BYTE InfoType);
void call_firstposition_info();
void call_secondposition_info();
void call_domain_info();
void call_folder_info(WORD FolderNo, BYTE InfoType, BYTE PageNo);
void call_file_type_info(WORD FolderNo, WORD FileNo);
void call_secondposition_ns_info(WORD FirstPosition);
void call_stream_attribute_info(BYTE StType, BYTE StNo);
void call_play_info();
void call_media_play_info();
void call_audio_set_info();
void call_st_info();
void call_copy_info();
void call_cci_info();
void set3v_back_video(BYTE BackVideo, BYTE YSignal, BYTE CbSignal, BYTE CrSignal);
void set3v_video_adjust(BYTE BSign, BYTE Brightness, BYTE CtSign, BYTE Contrast, BYTE ClSign, BYTE Color, BYTE TSign, BYTE Tint);
void set3a_drc(BYTE DRCMode, BYTE CutScale, BYTE BoostScale);
void set3a_a_spk(BYTE CenterSize, BYTE RearSize, BYTE FrontSize, BYTE Sw);
void call_setup_info(BYTE FLDelay, BYTE FRDelay, BYTE CDelay, BYTE RLDelay, BYTE RRDelay, BYTE SwDelay);
void set3a_spk_lvl(BYTE FLSign, BYTE FLLevel);
void set3a_a_mute(BYTE DigitalMute, BYTE AnalogMute, BYTE SwMute, BYTE RLMute, BYTE RRMute, BYTE CMute, BYTE FLMute, BYTE FRMute);
void set3a_dm_mode(BYTE DmMode);
void set3a_dpl2_rf(BYTE SetMode, BYTE RDelay);
void set3a_phantom(BYTE Mode, BYTE Sign, BYTE Level);
void set3a_bassmng(BYTE Mode, BYTE BmFs);
void set2s_scan_time(BYTE Time, BYTE Skip);
void set2s_tv_aspect(BYTE SelectMode);
void set2s_dau_out(BYTE MPEG, BYTE DTS, BYTE Dolby, BYTE DtsDecode);
void set2a_play_priority(BYTE CD, BYTE VCD);
void set2a_lang(BYTE SPDisp, BYTE SelectMode, WORD LangCode);
void set2a_country_code(WORD CountryCode);
void set2a_ptl_lvl(BYTE Level, BYTE PtlPwd4, BYTE PtlPwd3, BYTE PtlPwd2);
void set2a_pause_mode(BYTE PauseMode);
void chg_tempptl(BYTE Permit);
void chg_media_mode(BYTE SelectMode);
void user_cont(BYTE SelectMode, WORD Selection);
void user_cont(BYTE SelectMode, WORD CoordinateX, WORD CoordinateY);
void set1_dvd(int regcode);
void testtone_output(BYTE Noise, BYTE SelectMode, BYTE Sw, BYTE Rs, BYTE Ls, BYTE C, BYTE Rf, BYTE Lf);
void search_play_unit_time(BYTE PlayMode, BYTE Speed, WORD FirstPosition, BYTE Hours, BYTE Minutes, BYTE Seconds);
void search_play_unit(BYTE PlayMode, BYTE Speed, WORD FirstPosition, WORD SecondPosition);
void search_play_time(BYTE PlayMode, BYTE Speed, BYTE Hours, BYTE Minutes, BYTE Seconds);
